Feature: Book Flight
  In order to know that the Book Flight page is operational
  As a website user
  I need to be able to book my flight

  Scenario: The book flight page is working.
    Given I am not logged in
    When I visit "book-flight"
    And I select "STL" from "Departure"
    And I select "ORD" from "Arrival"
    And I fill in "Departure Date" with date "next Monday"
    And I fill in "Return Date" with date "next Tuesday"
    And I enter "1" for "Adults"
    And I uncheck "Round trip?"
    And I press "Continue"
    Then the url should match "/book-flight/flight-selection"
    And I should see "Flights from St Louis to Chicago"
    And I check the first "departure_flight" radio
    And I press "Select Flight"
    Then the url should match "/book-flight/contact-information"
    And I select "Mr" from "Title"
    And I enter "John" for "First Name"
    And I enter "Doe" for "Last Name"
    And I enter "12300 Old Tesson Ferry Rd." for "Address Line 1"
    And I enter "Suite 200F" for "Address Line 2"
    And I enter "St. Louis" for "City"
    And I select "MO" from "State"
    And I enter "63128" for "Zip Code"
    And I select "1" from "Date of Birth Month"
    And I select "1" from "Date of Birth Day"
    And I select "1979" from "Date of Birth Year"
    And I enter "john.doe@airchoiceone.com" for "Email"
    And I enter "john.doe@airchoiceone.com" for "Repeat Email"
    And I enter "8664359847" for "Phone Number"
    And I enter "8664359847" for "Mobile Number"
    And I press "Save Contact Information"
    Then the url should match "/book-flight/seat-selection"
    And I press "No Thanks"
    Then the url should match "/book-flight/additional-services"
    And I press "Continue"
    Then the url should match "/book-flight/purchase"
    And I select "visa" from "paymentMethod[identifier]"
    And I enter "4111111111111111" for "Credit Card"
    And I enter "123" for "Credit CVV"
    And I enter "John Doe" for "Full Name"
    And I enter "12300 Old Tesson Ferry Rd." for "Address Line 1"
    And I enter "Suite 200F" for "Address Line 2"
    And I enter "St. Louis" for "City"
    And I select "MO" from "State"
    And I enter "63128" for "Zip Code"
    And I enter "8664359847" for "Phone Number"
    And I press "Continue to Confirm Purchase"
    Then the url should match "/book-flight/confirm"
    And I check "confirm"
    And I press "Confirm Purchase"
    Then the url should match "/your-confirmed-itinerary"
    And I should see "Your reservation has been confirmed."
